# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [2]:
print(np.__version__)

1.16.4


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
a.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
import random
x = np.array([random.randrange(10,49+1)])
x

array([18])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
x= np.array([1, 2, 3, 27,4,9]) 
print (x)
x1= x[::-1] 
x1

[ 1  2  3 27  4  9]


array([ 9,  4, 27,  3,  2,  1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
import numpy as np
x = np.random.randint(0,9,size=(3,3))
x

array([[8, 2, 1],
       [4, 2, 5],
       [0, 0, 6]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [32]:
a= np.array([1,2,0,0,4,0])
print(a)
x=np.nonzero(a)
print(x)

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
x = np.random.rand(3,3,3)
x

array([[[0.97284418, 0.81112807, 0.69778509],
        [0.28446144, 0.75550047, 0.93109831],
        [0.95516365, 0.58319464, 0.76492863]],

       [[0.52812635, 0.89680563, 0.98615658],
        [0.5492117 , 0.02488114, 0.8172438 ],
        [0.58923659, 0.51084224, 0.11739587]],

       [[0.77448989, 0.689171  , 0.11399583],
        [0.96739119, 0.69668337, 0.49690081],
        [0.7680066 , 0.36106188, 0.36820721]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
np.random.seed(12)
x = np.random.rand(3,3)
print(x)
print(np.min(x))
print(np.max(x))

[[0.15416284 0.7400497  0.26331502]
 [0.53373939 0.01457496 0.91874701]
 [0.90071485 0.03342143 0.95694934]]
0.014574962485419674
0.9569493362751168


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
x = np.random.random(30)
print(x)
np.mean(x)

[0.13720932 0.28382835 0.60608318 0.94422514 0.85273554 0.00225923
 0.52122603 0.55203763 0.48537741 0.76813415 0.16071675 0.76456045
 0.0208098  0.13521018 0.11627302 0.30989758 0.67145265 0.47122978
 0.8161683  0.28958678 0.73312598 0.70262236 0.32756948 0.33464753
 0.97805808 0.62458211 0.95031352 0.76747565 0.82500925 0.4066403 ]


0.5186355181204115

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("/n")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
/n
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [15]:
x = np.random.rand(4,4)
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0.45130841 0.40063163 0.99513816 0.17756418]
 [0.9625969  0.41925027 0.42405245 0.46314887]
 [0.37372315 0.4655081  0.03516826 0.08427267]
 [0.7325207  0.63619999 0.02790779 0.30017006]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.45130841 0.40063163 0.99513816 0.17756418 0.        ]
 [0.         0.9625969  0.41925027 0.42405245 0.46314887 0.        ]
 [0.         0.37372315 0.4655081  0.03516826 0.08427267 0.        ]
 [0.         0.7325207  0.63619999 0.02790779 0.30017006 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
#False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [35]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [16]:
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [53]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [17]:
def checher(n):
    x = np.zeros((n,n))
    x[1::2,::2] = 1
    x[::2,1::2] = 1
    return x
print(checher(8))


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [18]:
import numpy as np
x= np.random.random((3,3))
print(x)
print("\n")
xmax = x.max()
xmin = x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.22085252 0.05501999 0.52324607]
 [0.41636966 0.04821875 0.57240452]
 [0.80351665 0.11360172 0.27711721]]


[[0.22856382 0.00900472 0.6289271 ]
 [0.48742477 0.         0.69401195]
 [1.         0.0865658  0.3030572 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [47]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [36]:
x = np.random.random((5,3))
print(x)
y = np.random.random((3,2))
print(y)
z = np.dot(x, y)
print("Multiply:")
print(z)

[[0.20850049 0.94458146 0.07347004]
 [0.59515246 0.03115107 0.66525743]
 [0.6373855  0.86246516 0.94163771]
 [0.44562705 0.66995763 0.9243307 ]
 [0.61942347 0.32258573 0.31947631]]
[[0.29145669 0.95741742]
 [0.40595834 0.94655582]
 [0.85719056 0.68892767]]
Multiply:
[[0.50720741 1.14433663]
 [0.75635959 1.05760981]
 [1.34305815 2.07533567]
 [1.19418342 1.69760039]
 [0.58534356 1.11848829]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [55]:
a=np.arange(20)
x = (a > 2) & (a < 8)
a[x] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [49]:
#10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [51]:
Z=np.array([1, 2, 3, 27,4,9]) 
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [56]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


D:\Programme\Annaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Programme\Annaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [19]:
array1 = np.array([5,7,9,12,14,17])
array2 = [12, 30, 40]
print(np.intersect1d(array1, array2))

[12]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [20]:
#False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [21]:
import numpy as np
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print("Yestraday:",yesterday)
today     = np.datetime64('today','D')
print("Today:",today)
tomorrow  = np.datetime64('today','D') + np.timedelta64(1, 'D')
print("Tomorrow:",tomorrow)

Yestraday: 2020-04-02
Today: 2020-04-03
Tomorrow: 2020-04-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [52]:
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [67]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [22]:
x = np.zeros((5,5))
print(x)
x += np.arange(5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [23]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [24]:
a= np.random.rand(10)
print(a)
np.sort(a)

[0.64167809 0.49273731 0.50655608 0.46144026 0.89474307 0.60577769
 0.6033556  0.44387186 0.48004678 0.88844753]


array([0.44387186, 0.46144026, 0.48004678, 0.49273731, 0.50655608,
       0.6033556 , 0.60577769, 0.64167809, 0.88844753, 0.89474307])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)